name: osti 
channels:
  - defaults 
dependencies:
  - python=3.6
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - autopep8=1.4.3
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - cffi=1.12.1
  - chardet=3.0.4
  - colorama=0.4.1
  - cryptography=2.5
  - cycler=0.10.0
  - decorator=4.3.2
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - freetype=2.9.1
  - gitdb2=2.0.5
  - gitpython=2.1.11
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - jdcal=1.4
  - jedi=0.13.3
  - jinja2=2.10
  - jsonschema=2.6.0
  - jupyter_client=5.2.4
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.4.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.36
  - libsodium=1.0.16
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.3.1
  - markupsafe=1.1.1
  - matplotlib=3.0.2
  - mistune=0.8.4
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.0
  - nbconvert=5.3.1
  - nbdime=1.0.4
  - nbformat=4.4.0
  - nbstripout=0.3.3
  - ncurses=6.1
  - nodejs=10.13.0
  - notebook=5.7.4
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openpyxl=2.6.0
  - openssl=1.1.1b
  - pandas=0.24.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.4
  - patsy=0.5.1
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pygments=2.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.3.1
  - pysocks=1.6.8
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pyyaml=3.13
  - pyzmq=18.0.0
  - readline=7.0
  - requests=2.21.0
  - scikit-learn=0.20.2
  - scipy=1.2.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=40.8.0
  - six=1.12.0
  - smmap2=2.0.5
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - xlrd=1.2.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
